Repository sk66641/Random-Disco-Light-Simulator, pull requests merged in 2024-08, with the labels that each got.

#557 ✔️Added Dynamic "Last Updated" Functionality to All Legal Pages !
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level2

#559 UI Improvement of contributors page
  pages/contributors.html
Labels: gssoc, level2

#562 Designed and Added A New "Logo" and A New "Favicon"
  assets/images/favicon.ico
  assets/images/favicon/favicon.ico
  assets/images/logo/logo..png
  css/style.css
  index.html
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: enhancement, gssoc, level2

#567 Fixes #564
  README.md
Labels: gssoc, level1

#569 FAQ's changes for better UI
  css/faq.css
  js/faq.js
  pages/faq.html
Labels: gssoc, level1

#570 Added Hover Scale on homebutton
  css/backtohome.css
Labels: gssoc, level1

#571 Add "Preloader" to All Pages (excluding Homepage)
  404.html
  css/preloader.css
  index.html
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level2

#574 Load once
  js/script.js
Labels: gssoc, level1

#582 removed the new logo from the login page
  Login/index1.html
Labels: gssoc, level1

#585 Update privacy.html
  pages/privacy.html
Labels: gssoc, level1

#588 Added trail cursor on login page
  Login/index1.html
Labels: gssoc, level1

#589 Change box color
  css/style.css
Labels: gssoc, level1

#590 Feedback scroll
  pages/features.html
  pages/feedback.html
Labels: gssoc, level1

#594 Fixed the Bug in Contributors Data Fetching in Contributors Page
  pages/contributors.html
Labels: gssoc, level2

#598 Added pop-up error message for unfilled fields
  index.html
  js/script.js
Labels: good first issue, gssoc, level1

#604 Fixed preloader bug
  404.html
  css/preloader.css
  js/preloader.js
  js/script.js
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/licensing.html
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level2

#608 ✔️Added Diagonal-Hovering Effect to Each Card!
  pages/contributors.html
Labels: gssoc, level2

#609 Made Minor changes in Terms and conditions
  pages/terms.html
Labels: gssoc, level1

#611 fixed the copyright
  pages/licensing.html
Labels: gssoc, level1

#613 adding icons to side bar
  css/style.css
  index.html
  js/script.js
  pages/licensing.html
Labels: gssoc, level1

#614 Updated UI Improvement buttons
  css/style.css
Labels: gssoc, level2

#617 added captcha to the login page
  Login/index1.html
  Login/script1.js
  Login/styles1.css
Labels: enhancement, gssoc, level3

#612 Corrected multiple pages
  css/about.css
  css/features.css
  css/style.css
Labels: bug, gssoc, level1

#620 added the aria labels for all the pages which were missing it
  pages/about.html
  pages/faq.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: enhancement, gssoc, level3

#623 preloader on signup page
  Login/index1.html
  css/style.css
Labels: gssoc, level1

#627 fixed the star bug
  pages/feedback.html
Labels: bug, gssoc, level1

#622 Updated the Light Pattern Options In website
  index.html
  js/script.js
Labels: gssoc, level2

#626 Faq enhancement
  css/faq.css
  pages/faq.html
Labels: gssoc, level1

#635 Added testimonials
  index.html
  pages/testimonials.html
Labels: gssoc, level3, level updated

#638 added missing data in the input
  pages/about.html
Labels: gssoc, level1

#640 Removing unused code and extra spaces for all pages
  pages/about.html
  pages/contributors.html
  pages/features.html
  pages/feedback.html
Labels: gssoc, level2

#642 Fixing pause font
  index.html
  js/script.js
Labels: bug, gssoc, level1
