Repository sk66641/Random-Disco-Light-Simulator, pull requests merged in 2024-07, with the labels that each got.

#378 i have added the social media pop up in all the pages
  index.html
  js/script.js
  js/social.js
  pages/about.html
  pages/features.html
  pages/feedback.html
Labels: gssoc, level1

#446 Adding Home icon in Privacy Policy,Terms and Conditions Page,Setting Linking and Adding Privacy Policy,Terms and Conditions Page in sidebar
  .vscode/settings.json
  index.html
  pages/about.html
  pages/faq.html
  pages/feedback.html
Labels: gssoc, level1

#452 Improved FAQ Page
  css/faq.css
  pages/faq.html
Labels: gssoc, level1

#450 FAQ box width fixed
  css/style.css
Labels: gssoc, level1

#451 Changed the font family of the website .
  404.html
  css/404.css
  css/about.css
  css/faq.css
  css/features.css
  css/feedback.css
  css/style.css
  index.html
  pages/about.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level1

#459 ✔️ Improved the "Back to Home" Button in All Pages!
  assets/images/BackToHome Btn.png
  css/backtohome.css
  pages/about.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level2

#455 Added a "Cursor Trail effect" to the website
  css/style.css
  index.html
  js/script.js
  pages/about.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
Labels: gssoc, level2

#460 Added Contributor page
  css/contributors.css
  index.html
  pages/contributors.html
Labels: gssoc, level3, level updated

#462 ✔️ Improved "Complete UI and Functionality" Of the Feedback Form
  assets/images/comments.png
  assets/images/email.png
  assets/images/stars.png
  assets/images/user.png
  css/feedback.css
  pages/feedback.html
Labels: gssoc, level2

#463 Update README.md features section
  README.md
Labels: documentation, gssoc, level1

#468 Added mode toggler in privacy policy and Terms page
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level1

#456 Change music in paused/muted state
  js/script.js
Labels: gssoc, level1

#472 Hide The Trail Effect in Mobile View
  index.html
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
Labels: gssoc, level1

#474 Corrected Redirect path
  404.html
Labels: gssoc, level1

#477 Corrected social media icons positions
  index.html
Labels: gssoc, level1

#458 Responsive between 400-300
  css/style.css
  index.html
Labels: gssoc, level2

#485 📝[Docs]: Adding Installation and Setup Guide
  Learn.md
  README.md
Labels: documentation, gssoc, level1

#486 Added featured in section
  README.md
Labels: documentation, gssoc, level1

#483 Add Required Meta Tags to Improve SEO Performance
  404.html
  Login/index1.html
  index.html
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level1

#502 Corrected labels on hover of the stars .
  pages/feedback.html
Labels: gssoc, level1

#503 Style to select language
  css/style.css
Labels: gssoc, level1

#501 Fixed The Overlapping Chatbot and Scroll to Top Button
  css/style.css
  index.html
  js/backToTopBtn.js
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level3

#522 Issue #517
  js/script.js
Labels: bug, enhancement, gssoc, level1

#523 Added light/dark mode feature on all the pages .
  css/mode_toggler.css
  index.html
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level3

#524 Preset Modals and Notifications
  index.html
  js/script.js
Labels: gssoc, level2

#530 Change the Content in About Section
  pages/about.html
Labels: gssoc, level1

#531 Fix Feedback message image
  pages/feedback.html
Labels: gssoc, level1

#535 Theme toggle error
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
Labels: gssoc, level2, level updated

#534 Corrected Back-To-Top button
  css/backToTopButton.css
  css/style.css
  index.html
  js/backToTopBtn.js
Labels: gssoc, level2, level updated

#538 Theme toggle
  css/about.css
  css/faq.css
  css/features.css
  css/feedback.css
  css/mode_toggler.css
  css/style.css
  index.html
  js/script.js
  js/theme.js
  pages/about.html
  pages/contributors.html
  pages/faq.html
  pages/features.html
  pages/feedback.html
  pages/privacy.html
  pages/terms.html
Labels: gssoc, level2

#540 Removing unnecessary code from index.html
  index.html
Labels: gssoc, level1
