Repository sk66641/Random-Disco-Light-Simulator, pull requests merged in 2024-05, with the labels that each got.

#34 added workflow as per issue #13
  .github/workflows/autocomment-issue.yml
Labels: gssoc, level2

#38 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: gssoc, level2

#50 Added the logo
  index.html
  logo.jpg
  style.css
Labels: gssoc

#81 Added Sound effects #61
  assets/audios/Snare.mp3
  assets/audios/omniscent.mp3
  assets/audios/vintage.mp3
  assets/audios/whistle.mp3
  index.html
  style.css
Labels: gssoc, level1
